backend:
  name: git-gateway
  branch: cto
media_folder: public/img
public_folder: img
site_url: https://butwillitscale.com
logo_url: https://butwillitscale.com/img/download.png
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/home.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Body", name: "body", widget: "markdown" }
          - label: "Cats"
            name: "cats"
            widget: list
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
          - label: "Featured Posts"
            name: "featured"
            widget: "relation"
            collection: "blog"
            valueField: "slug"
            displayFields: "title"
            searchFields: ["title"]
            multiple: true
      - label: "Solutions"
        name: "solutions"
        file: "content/solutions.md"
        fields:
          - {
              label: "Public",
              name: "public",
              widget: "boolean",
              default: true,
            }
          - { label: "Name", name: "name", widget: "string" }
          - label: "Birthdate"
            name: "birthdate"
            widget: "date"
            default: ""
            format: "MM/DD/YYYY"
          - label: "Features"
            name: "features"
            widget: "object"
            fields:
              - label: "Feature 1"
                name: "feature1"
                widget: "object"
                fields:
                  - { label: "Heading", name: "heading", widget: "string" }
                  - { label: "Blurb", name: "blurb", widget: "text" }
              - label: "Feature 2"
                name: "feature2"
                widget: "object"
                fields:
                  - { label: "Heading", name: "heading", widget: "string" }
                  - { label: "Blurb", name: "blurb", widget: "text" }
              - label: "Feature 3"
                name: "feature3"
                widget: "object"
                fields:
                  - { label: "Heading", name: "heading", widget: "string" }
                  - { label: "Blurb", name: "blurb", widget: "text" }
      - label: "Registry"
        name: "registry"
        file: "content/registry.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Body", name: "body", widget: "markdown" }
          - label: "Cats"
            name: "cats"
            widget: list
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
  - name: "blog"
    label: "Blog"
    folder: "content/posts"
    preview_path: "posts/{{slug}}"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
          label: "Featured Image",
          name: "thumbnail",
          widget: "image",
          required: false,
        }
      - {
          label: "Rating (scale of 1-5)",
          name: "rating",
          widget: "number",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }
